### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by djkost85** [MozzieMD/PHP-Mail.Ru-video#1]
Hello, 

Thank you for sharing you script,
I have some problem to execute the script my server give me this error " PHP Parse error:  syntax error, unexpected '[' in MailRU.class.php on line 39".
on my test i have used your proper example for use in readme.

Please, can verify this

**Comment by MozzieMD** [comment]
Do you still have this problem? because there is everything right

**Comment by djkost85** [comment]
on line 39 i have modify the script using: 
$value = explode("video_key=",$header);
$value = $value[1];
by this modification it work perfectly. but when i try to download the link of video i have a nice 403 Forbidden error.

**Comment by MozzieMD** [comment]
because you need video_key=hash cookie in your browser to download the video, or in php use curl and send cookie header with that video_key using `$mail->VideoKey();`

**Comment by djkost85** [comment]
Please, can you provide me an example

**Comment by MozzieMD** [comment]
check this page, http://www.w3bees.com/2013/09/download-file-from-remote-server-with.html, and search on stackoverflow about sending cookie with curl... nothing hard!

**Comment by djkost85** [comment]
Thank you.
